// Premium Luxury Gemstones Database
const GemstoneDB = {
  products: [
    // === EXCLUSIVE GEMSTONES ===
    {
      id: "alexandrite-stone",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1r9bF5CYr--RAqeXpFKRRcSc2ae6Q5E_i=w400-h400-p",
      name: "Ultra Rare Natural Alexandrite Stone",
      sku: "EX-ALX-001",
      category: "precious",
      subCategory: "alexandrite",
      color: "Color-Changing (Green to Red)",
      origin: "Ceylon (Sri Lanka)",
      shape: "Oval Mixed Cut",
      weight: "2.40",
      clarity: "Eye Clean",
      treatment: "100% Unheated & Untreated",
      certificate: "GIA Certified",
      price: 4850,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 16,
      image: "alexandrite",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1r9bF5CYr--RAqeXpFKRRcSc2ae6Q5E_i=w400-h400-p",
      description: "A highly rare color-changing natural Alexandrite from Ceylon. Shifts from a rich forest green under daylight to a purplish-red under incandescent lighting. Highly prized by collectors and astrologers for its massive cosmic potency.",
      specifications: {
        "Carat Weight": "2.40 Carat (2.66 Ratti)",
        "Origin": "Ceylon, Sri Lanka",
        "Color": "Forest Green to Purplish Red",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "No Indication of Treatment (Unheated)",
        "Certification": "GIA (Gemological Institute of America)",
        "Clarity": "Eye Clean",
        "Dimensions": "8.4 x 6.2 x 4.1 mm",
        "Planet": "Mercury & Rahu",
        "Zodiac": "Gemini (Mithun), Virgo (Kanya)",
        "Metal Recommendation": "Platinum or White Gold"
      },
      astrology: {
        planet: "Mercury",
        rashi: ["Gemini", "Virgo"],
        birthstone: "June",
        benefits: ["Brings immense creativity and wealth", "Acts as a protective shield against evil eyes", "Balances intellectual and emotional wavelengths", "Enhances communication skills and public confidence"]
      },
      faqs: [
        { q: "Why is Alexandrite called 'Emerald by day, Ruby by night'?", a: "Alexandrite contains chromium, which causes it to absorb light in a way that shifts its visible color from green under daylight to red under warm lighting." },
        { q: "Who should wear Alexandrite?", a: "Astrologers recommend it for Gemini and Virgo ascendants, as well as those going through Mercury or Rahu Mahadashas." }
      ],
      reviews: [
        { user: "Devendra Mehta", rating: 5, date: "May 20, 2026", comment: "The color shift is absolutely dramatic! Verified with GIA registry instantly. Very premium service." }
      ]
    },
    {
      id: "burmese-ruby-old",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1iiTjgPEUCN1Bs53v1EJAhsmdn1_bDDaE=w400-h400-p",
      name: "Untreated Burmese Ruby Stone (Old Burma)",
      sku: "EX-RUB-002",
      category: "precious",
      subCategory: "ruby",
      color: "Pigeon Blood Red",
      origin: "Mogok (Burma)",
      shape: "Oval Cut",
      weight: "2.20",
      clarity: "Slightly Included (Typical Natural)",
      treatment: "No Heat / 100% Untreated",
      certificate: "GRS Certified",
      price: 3950,
      currency: "USD",
      rating: 5.0,
      reviewsCount: 31,
      image: "ruby",
      description: "An authentic, historic Mogok Old Burma Pigeon Blood Ruby. Completely unheated and untreated, possessing the classic strong fluorescent crimson glow that cannot be replicated. Maximum astrological benefits for leadership and fame.",
      specifications: {
        "Carat Weight": "2.20 Carats (2.44 Ratti)",
        "Origin": "Mogok, Burma (Myanmar)",
        "Color": "Pigeon Blood Red",
        "Shape/Cut": "Oval Cushion Cut",
        "Treatment": "No Indication of Heating (Unheated)",
        "Certification": "GRS (Gem Research Swisslab)",
        "Clarity": "Slightly Included (Eye Clean Table)",
        "Dimensions": "7.9 x 6.1 x 3.8 mm",
        "Planet": "Sun (Surya)",
        "Zodiac": "Leo (Simha)",
        "Metal Recommendation": "22k Yellow Gold"
      },
      astrology: {
        planet: "Sun",
        rashi: ["Leo"],
        birthstone: "July",
        benefits: ["Bestows high leadership qualities and power", "Clears self-doubt and triggers peak confidence", "Boosts cardiovascular health and vitality", "Attracts social reputation and royal authority"]
      },
      faqs: [
        { q: "What makes Burmese Rubies so expensive?", a: "The historic mines of Mogok produce rubies with high chromium content and low iron, giving them a glowing red fluorescence that is extremely rare in nature." }
      ],
      reviews: [
        { user: "Rajesh Singhal", rating: 5, date: "May 15, 2026", comment: "Outstanding fire and glow! Wore it on a Sunday morning and felt an immediate energy boost." }
      ]
    },
    {
      id: "colombian-emerald-panna",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1yUOb4Kw2hcpyExvzpDE2J3iPe2m7ZaEH=w400-h400-p",
      name: "Premium Colombian Emeralds (Colombian Panna)",
      sku: "EX-EME-003",
      category: "precious",
      subCategory: "emerald",
      color: "Vivid Green",
      origin: "Muzo (Colombia)",
      shape: "Emerald Octagon Cut",
      weight: "2.40",
      clarity: "Insignificant Oil",
      treatment: "Standard Natural Oil Only",
      certificate: "GIA Certified",
      price: 3200,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 22,
      image: "emerald",
      description: "A gorgeous, highly luminous vivid green emerald from the legendary Muzo mines of Colombia. Standard light oil only, featuring exceptional transparent crystal clarity that is extremely rare for Colombian Panna.",
      specifications: {
        "Carat Weight": "2.40 Carat (2.66 Ratti)",
        "Origin": "Muzo, Colombia",
        "Color": "Vivid Green",
        "Shape/Cut": "Octagonal Step Cut",
        "Treatment": "Insignificant Clarification (Minor Natural Oil)",
        "Certification": "GIA Certified",
        "Clarity": "Transparent",
        "Dimensions": "8.8 x 6.9 x 4.3 mm",
        "Planet": "Mercury (Budh)",
        "Zodiac": "Gemini (Mithun), Virgo (Kanya)",
        "Metal Recommendation": "Gold or Silver"
      },
      astrology: {
        planet: "Mercury",
        rashi: ["Gemini", "Virgo"],
        birthstone: "May",
        benefits: ["Dramatically improves business success and wealth", "Sharpens mathematical and analytical intelligence", "Cures speech hesitation and enhances public speaking", "Acts as an exceptional study charm for scholars"]
      },
      faqs: [
        { q: "Why do Colombian Emeralds have inclusions?", a: "Natural emeralds are formed under intense tectonic stress. Inclusions, known as 'jardin' (garden), are proof of their organic origins." }
      ],
      reviews: []
    },
    {
      id: "cornflower-blue-sapphire",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1ammDYoNefkAvF58TqdrsTAO2OjSG7imy=w400-h400-p",
      name: "Natural Cornflower Blue Sapphire",
      sku: "EX-SAP-004",
      category: "precious",
      subCategory: "blue-sapphire",
      color: "Cornflower Blue",
      origin: "Ceylon (Sri Lanka)",
      shape: "Oval Mixed Cut",
      weight: "2.40",
      clarity: "Eye Clean",
      treatment: "100% Unheated",
      certificate: "GRS Certified",
      price: 2900,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 19,
      image: "blue-sapphire",
      description: "A highly brilliant, rare Cornflower Blue Sapphire from the alluvial beds of Elahera, Ceylon. Features a beautifully saturated medium-blue tone with classic silky reflections.",
      specifications: {
        "Carat Weight": "2.40 Carat (2.66 Ratti)",
        "Origin": "Ceylon, Sri Lanka",
        "Color": "Cornflower Blue",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "No Indication of Thermal Treatment",
        "Certification": "GRS Certified",
        "Clarity": "Eye Clean",
        "Dimensions": "8.5 x 6.5 x 4.0 mm",
        "Planet": "Saturn (Shani)",
        "Zodiac": "Capricorn (Makar), Aquarius (Kumbh)",
        "Metal Recommendation": "White Gold or Silver"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius"],
        birthstone: "September",
        benefits: ["Brings instant professional opportunities", "Strengthens decision-making and vision clarity", "Acts as a powerful shield from psychic attacks", "Aligns the crown and third-eye chakras"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "kashmir-blue-sapphire",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1ZN_PcxTNN7r_yzGlFfNTDFstdL_D-s2_=w400-h400-p",
      name: "Legendary Kashmir Blue Sapphire Stone",
      sku: "EX-SAP-005",
      category: "precious",
      subCategory: "blue-sapphire",
      color: "Velvety Royal Blue",
      origin: "Kashmir (India)",
      shape: "Cushion Cut",
      weight: "2.20",
      clarity: "Eye Clean Table",
      treatment: "100% Unheated",
      certificate: "GRS Certified",
      price: 8500,
      currency: "USD",
      rating: 5.0,
      reviewsCount: 12,
      image: "blue-sapphire",
      description: "An incredibly rare velvety Royal Blue Sapphire from the historic Padar mines of Kashmir. Exhibits the legendary 'velvet' luster caused by fine rutile silk inclusions that disperse light perfectly. A once-in-a-lifetime astrological acquisition.",
      specifications: {
        "Carat Weight": "2.20 Carat (2.44 Ratti)",
        "Origin": "Kashmir, India",
        "Color": "Royal Blue (Velvety)",
        "Shape/Cut": "Cushion Mixed Cut",
        "Treatment": "Unheated & Untreated",
        "Certification": "GRS Certified with Origin Report",
        "Clarity": "Highly Luminous Velvet",
        "Dimensions": "8.0 x 6.0 x 4.2 mm",
        "Planet": "Saturn (Shani)",
        "Zodiac": "Capricorn (Makar), Aquarius (Kumbh)",
        "Metal Recommendation": "Platinum or 18k White Gold"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius"],
        birthstone: "September",
        benefits: ["Fastest acting stone for luck, fame, and abundance", "Restores lost business and balances karmic cycles", "Offers massive relief from chronic nervous disorders", "Imparts deep mental peace and spiritual alignment"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "no-oil-emerald",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1QMpN2dHajKmLyA286EeBdBRiVEq_fImk=w400-h400-p",
      name: "Rare 'No Oil' Colombian Emerald",
      sku: "EX-EME-006",
      category: "precious",
      subCategory: "emerald",
      color: "Vivid Green",
      origin: "Colombia",
      shape: "Emerald Cut",
      weight: "2.60",
      clarity: "Vividly Transparent",
      treatment: "No Oil / 100% Pristine",
      certificate: "GIA Certified",
      price: 5200,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 15,
      image: "emerald",
      description: "An extraordinarily rare GIA-certified 'No Oil' Emerald from Colombia. Over 99% of emeralds are oiled to fill surface-reaching fractures; this natural crystal is so pristine it requires zero clarification. Pure astrological channeler.",
      specifications: {
        "Carat Weight": "2.60 Carats (2.88 Ratti)",
        "Origin": "Chivor, Colombia",
        "Color": "Vivid Emerald Green",
        "Shape/Cut": "Emerald Octagon Cut",
        "Treatment": "No Indication of Clarity Enhancement (No Oil)",
        "Certification": "GIA Certified",
        "Clarity": "Pristine Transparency",
        "Dimensions": "9.1 x 7.0 x 4.5 mm",
        "Planet": "Mercury (Budh)",
        "Zodiac": "Gemini (Mithun), Virgo (Kanya)",
        "Metal Recommendation": "22k Yellow Gold"
      },
      astrology: {
        planet: "Mercury",
        rashi: ["Gemini", "Virgo"],
        benefits: ["Triggers maximum mental clarity and memory power", "Exceptional for wealth expansion and speculative gains", "Aids in respiratory, speech, and neurological vitality", "Calms anxious thoughts and resolves planetary blockages"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "padparadscha-sapphire",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1ZMlbtBBBEsRWYd22R5vPmr4DgC0n28tv=w400-h400-p",
      name: "Exquisite Orangey-Pink Padparadscha",
      sku: "EX-SAP-007",
      category: "precious",
      subCategory: "yellow-sapphire",
      color: "Orangey-Pink (Lotus Blossom)",
      origin: "Ceylon (Sri Lanka)",
      shape: "Oval Cut",
      weight: "2.30",
      clarity: "Eye Clean",
      treatment: "100% Unheated",
      certificate: "GRS Certified",
      price: 4300,
      currency: "USD",
      rating: 5.0,
      reviewsCount: 8,
      image: "yellow-sapphire",
      description: "The absolute crown jewel of the sapphire family—a GRS-certified natural Padparadscha Sapphire. Exhibits the delicate blend of lotus-pink and sunset-orange that defines this legendary stone. Combines the cosmic powers of Jupiter and the Sun.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Ceylon, Sri Lanka",
        "Color": "Orangey-Pink",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "Unheated & Untreated",
        "Certification": "GRS Certified (Special Color Grade)",
        "Clarity": "Eye Clean",
        "Planet": "Jupiter & Sun",
        "Zodiac": "Sagittarius (Dhanu), Leo (Simha)",
        "Metal Recommendation": "18k Rose Gold or Gold"
      },
      astrology: {
        planet: "Jupiter",
        rashi: ["Sagittarius", "Pisces", "Leo"],
        benefits: ["Attracts celestial wisdom and professional expansion", "Brings absolute harmony, joy, and luck in relationships", "Activates solar plexus and heart chakra energies", "Elevates spiritual progress and administrative skills"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "panjshir-emerald",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1SroB0rsWr-F43pC-qagjJtqEySNNoAIQ=w400-h400-p",
      name: "Afghanistan Panjshir Emerald",
      sku: "EX-EME-008",
      category: "precious",
      subCategory: "emerald",
      color: "Bright Green",
      origin: "Panjshir (Afghanistan)",
      shape: "Emerald Octagon Cut",
      weight: "2.50",
      clarity: "Highly Luminous",
      treatment: "Insignificant Oil",
      certificate: "IGI Certified",
      price: 2600,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 14,
      image: "emerald",
      description: "A highly reflective, bright green natural emerald from the mountainous Panjshir Valley of Afghanistan. Exhibits extreme color saturation and purity comparable to elite Colombian gems.",
      specifications: {
        "Carat Weight": "2.50 Carats (2.77 Ratti)",
        "Origin": "Panjshir, Afghanistan",
        "Color": "Vivid Bluish-Green",
        "Shape/Cut": "Octagonal Step Cut",
        "Treatment": "Minor Clarity Oil Only",
        "Certification": "IGI Laboratory Certified",
        "Clarity": "High Transparency",
        "Planet": "Mercury (Budh)"
      },
      astrology: {
        planet: "Mercury",
        rashi: ["Gemini", "Virgo"],
        benefits: ["Imparts unparalleled articulation and sharp memory", "Protects from trade losses and guides commercial growth", "Reduces nervous stress and balances body temperature", "Brings academic distinction and creative excellence"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "paraiba-tourmaline",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1jEqZVjBFszvjgsmsYuyx6kS8kx9FIuSc=w400-h400-p",
      name: "Neon Blue Paraiba Tourmaline",
      sku: "EX-TOR-009",
      category: "semi-precious",
      subCategory: "tourmaline",
      color: "Neon Copper Blue-Green",
      origin: "Batalha (Brazil)",
      shape: "Oval Cut",
      weight: "2.30",
      clarity: "Eye Clean Table",
      treatment: "Standard Heat Only",
      certificate: "GRS Certified",
      price: 4950,
      currency: "USD",
      rating: 5.0,
      reviewsCount: 7,
      image: "blue-sapphire",
      description: "An elite cuprian Paraiba Tourmaline from Batalha, Brazil. Houses a unique copper-manganese atomic structure that generates an electric neon glow even under dim twilight. Exceptional aura balancing capabilities.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Batalha, Brazil",
        "Color": "Neon Electric Turquoise",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "Standard Mild Heating Only (Stabilized)",
        "Certification": "GRS Certified with Cuprian Analysis",
        "Clarity": "Eye Clean Table",
        "Planet": "Venus & Mercury",
        "Zodiac": "Taurus (Vrish), Libra (Tula)"
      },
      astrology: {
        planet: "Venus",
        rashi: ["Taurus", "Libra", "Gemini"],
        benefits: ["Attracts luxury, extreme comfort, and high-end lifestyle", "Balances throat chakra and enhances modern creative ventures", "Protects from psychological blocks and toxic vibrations", "Triggers deep passion, charisma, and public appeal"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "pigeon-blood-ruby",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1CXKaU6R3akBpxuxzwYIoWEnvfU6-e7s6=w400-h400-p",
      name: "Elite Burmese Pigeon Blood Ruby",
      sku: "EX-RUB-010",
      category: "precious",
      subCategory: "ruby",
      color: "Vivid Pigeon Blood Red",
      origin: "Burma (Myanmar)",
      shape: "Oval Cushion Cut",
      weight: "2.20",
      clarity: "Eye Clean",
      treatment: "100% Unheated",
      certificate: "GIA Certified",
      price: 4100,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 20,
      image: "ruby",
      description: "A textbook Pigeon Blood Ruby from the classic Burma basins. Certified completely unheated with zero glass fills, showcasing the purest royal scarlet tone with intense internal dispersion.",
      specifications: {
        "Carat Weight": "2.20 Carat (2.44 Ratti)",
        "Origin": "Mogok, Burma",
        "Color": "Vivid Pigeon Blood Red",
        "Shape/Cut": "Oval Cushion Cut",
        "Treatment": "No Indication of Heating",
        "Certification": "GIA Laboratory Certified",
        "Clarity": "Transparent (Type II)",
        "Planet": "Sun (Surya)"
      },
      astrology: {
        planet: "Sun",
        rashi: ["Leo"],
        birthstone: "July",
        benefits: ["Elevates leadership authority, administrative power, and fame", "Dispels fear, lethargy, and negative self-talk instantly", "Aids in strong cardiovascular and circulatory health", "Fuels administrative careers and social recognition"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "pink-sapphire-stone",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/18nwQV41S2KGCOHutYXFjufQwD6voe_Vw=w400-h400-p",
      name: "Natural Sri Lankan Pink Sapphire",
      sku: "EX-SAP-011",
      category: "precious",
      subCategory: "amethyst",
      color: "Hot Vivid Pink",
      origin: "Ceylon (Sri Lanka)",
      shape: "Oval Cut",
      weight: "2.30",
      clarity: "Eye Clean",
      treatment: "100% Unheated",
      certificate: "GRS Certified",
      price: 2300,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 11,
      image: "amethyst",
      description: "A highly lustrous Ceylon hot pink sapphire. Unheated and untreated, providing an exceptional option for strengthening the energetic alignments of Venus and Sun.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Ceylon, Sri Lanka",
        "Color": "Vivid Pink",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "Unheated & Untreated",
        "Certification": "GRS Lab Certified",
        "Clarity": "Eye Clean",
        "Planet": "Sun & Venus"
      },
      astrology: {
        planet: "Venus",
        rashi: ["Taurus", "Libra", "Leo"],
        benefits: ["Attracts romantic charm, marital bonding, and loyalty", "Amplifies artistic skills, beauty, and luxury pursuits", "Stabilizes emotional distress and strengthens self-worth", "Spurs popularity in glamour and public relations"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "royal-blue-sapphire",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1u3dxGu414AITWTv-2O4y_2iaysCF0SBJ=w400-h400-p",
      name: "Royal Blue Sapphire (Neelam)",
      sku: "EX-SAP-012",
      category: "precious",
      subCategory: "blue-sapphire",
      color: "Royal Blue",
      origin: "Ceylon (Sri Lanka)",
      shape: "Oval Mixed Cut",
      weight: "2.10",
      clarity: "Eye Clean",
      treatment: "100% Unheated",
      certificate: "GIA Certified",
      price: 2750,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 18,
      image: "blue-sapphire",
      description: "An outstanding, deep-saturated Royal Blue Sapphire from Sri Lanka. Sourced from the prestigious Ratnapura mines, certified fully unheated to guarantee raw astrological speed.",
      specifications: {
        "Carat Weight": "2.10 Carats (2.33 Ratti)",
        "Origin": "Ratnapura, Sri Lanka",
        "Color": "Royal Blue",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "Unheated & Untreated",
        "Certification": "GIA Certified",
        "Clarity": "Eye Clean (Excellent Luster)",
        "Planet": "Saturn (Shani)"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius"],
        benefits: ["Fast-tracks financial gains, business expansion, and clarity", "Shields from toxic entities, accidents, and psychological blocks", "Clears lethargy and drives strict discipline and success", "Balances planetary Saturn blockages in the birth chart"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "tanzanite-stone",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1kAa0ZKvoFyFB49_uSC0z3EVZM-7hLbFS=w400-h400-p",
      name: "Deep Velvet Tanzanite Stone",
      sku: "EX-TZN-013",
      category: "semi-precious",
      subCategory: "amethyst",
      color: "Deep Violet-Blue",
      origin: "Merelani (Tanzania)",
      shape: "Oval Cushion Cut",
      weight: "2.40",
      clarity: "Eye Clean",
      treatment: "Standard Thermal Only",
      certificate: "IGI Certified",
      price: 1350,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 10,
      image: "amethyst",
      description: "A highly saturated violet-blue Tanzanite from the single global deposit in the foothills of Mount Kilimanjaro, Tanzania. Offers extreme crystal transparency and elegant astrological substitution.",
      specifications: {
        "Carat Weight": "2.40 Carat (2.66 Ratti)",
        "Origin": "Merelani Hills, Tanzania",
        "Color": "Deep Violet-Blue",
        "Shape/Cut": "Oval Cushion Cut",
        "Treatment": "Standard Gentle Heating Only",
        "Certification": "IGI Lab Certified",
        "Clarity": "Eye Clean (Flawless Internal)",
        "Planet": "Saturn & Jupiter"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius", "Pisces"],
        benefits: ["Acts as a powerful substitute for Blue Sapphire (Neelam)", "Stimulates throat, third-eye, and crown chakras", "Brings deep administrative skills and financial growth", "Enhances memory, visual perception, and spiritual logic"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "vivid-green-emerald",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1IWpJ9CDELyxHLAkknrTSsPHs-PJ0bN6e=w400-h400-p",
      name: "Vivid Green Zambian Emerald",
      sku: "EX-EME-014",
      category: "precious",
      subCategory: "emerald",
      color: "Vivid Forest Green",
      origin: "Kagem (Zambia)",
      shape: "Emerald Octagon Cut",
      weight: "2.30",
      clarity: "Transparent Minor Oil",
      treatment: "Standard Oil Only",
      certificate: "GRS Certified",
      price: 2400,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 17,
      image: "emerald",
      description: "An exceptionally rich, bluish-green natural emerald from the Kagem mines of Zambia. Famous for its high iron content which gives it a deeply saturated, vivid green look under any light source.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Kagem, Zambia",
        "Color": "Vivid Bluish-Green",
        "Shape/Cut": "Octagonal Step Cut",
        "Treatment": "Insignificant Natural Oil Clarification",
        "Certification": "GRS Certified",
        "Clarity": "Highly Transparent",
        "Planet": "Mercury (Budh)"
      },
      astrology: {
        planet: "Mercury",
        rashi: ["Gemini", "Virgo"],
        benefits: ["Excellent for commerce, accounting, and leadership wins", "Sharpen communication skillsets and corporate speech", "Spurs strong digestive wellness and immune strength", "Acts as an auspicious charm for higher educational ranks"]
      },
      faqs: [],
      reviews: []
    },

    // === POPULAR VEDIC GEMS ===
    {
      id: "amethyst-stone-jamunia",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1Wzdei0kZya18keQsTDJzCZ6Wp0qNwlA0=w400-h400-p",
      name: "Deep Purple Brazilian Amethyst (Jamunia)",
      sku: "PO-AMY-001",
      category: "semi-precious",
      subCategory: "amethyst",
      color: "Deep Violet Purple",
      origin: "Rio Grande (Brazil)",
      shape: "Oval Mixed Cut",
      weight: "2.20",
      clarity: "Flawless",
      treatment: "100% Natural Unheated",
      certificate: "In-House Certified",
      price: 150,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 42,
      image: "amethyst",
      description: "An exquisite, deep purple Brazilian Amethyst (Jamunia). Sourced from the premium geode mines of Rio Grande, offering absolute crystal purity and astrological Saturn energy.",
      specifications: {
        "Carat Weight": "2.20 Carats (2.44 Ratti)",
        "Origin": "Rio Grande, Brazil",
        "Color": "Deep Violet",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "None (100% Natural)",
        "Clarity": "Flawless (No Inclusions)",
        "Planet": "Saturn (Shani)",
        "Zodiac": "Capricorn (Makar), Aquarius (Kumbh)"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius"],
        benefits: ["Prime substitute stone for Blue Sapphire (Neelam)", "Relieves chronic stress, anxiety, and sleep disorders", "Triggers deep spiritual focus and keeps negative patterns away", "Brings business stability and commercial success"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "citrine-stone-sunela",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1tEc_sJY1v9nVjZUVMmppIleJMHhDCmJ-=w400-h400-p",
      name: "Vibrant Citrine Stone (Sunela)",
      sku: "PO-CIT-002",
      category: "semi-precious",
      subCategory: "yellow-sapphire",
      color: "Golden Amber Yellow",
      origin: "Minas Gerais (Brazil)",
      shape: "Oval Cut",
      weight: "2.30",
      clarity: "Flawless",
      treatment: "100% Unheated",
      certificate: "In-House Certified",
      price: 180,
      currency: "USD",
      rating: 4.7,
      reviewsCount: 35,
      image: "yellow-sapphire",
      description: "A radiant, pure golden yellow Citrine (Sunela Stone) from Minas Gerais, Brazil. Absolutely unheated and natural, providing the perfect solar plexus chakra channeler.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Minas Gerais, Brazil",
        "Color": "Golden Yellow",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "Natural Unheated",
        "Clarity": "Flawless",
        "Planet": "Jupiter (Guru)"
      },
      astrology: {
        planet: "Jupiter",
        rashi: ["Sagittarius", "Pisces"],
        benefits: ["Excellent substitute for Yellow Sapphire (Pukhraj)", "Brings immense wealth, professional fortune, and high wisdom", "Acts as the ultimate positive vibe and self-confidence builder", "Ensures dynamic liver health, digestion, and systemic balance"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "fire-opal-mexican",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1HGWmhebcbfJ76QVja_ujyAjVB6BUFeY1=w400-h400-p",
      name: "Electric Mexican Fire Opal",
      sku: "PO-OPL-003",
      category: "semi-precious",
      subCategory: "opal",
      color: "Neon Orange-Red",
      origin: "Queretaro (Mexico)",
      shape: "Oval Cabochon",
      weight: "2.20",
      clarity: "Highly Translucent",
      treatment: "100% Untreated",
      certificate: "Laboratory Certified",
      price: 240,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 13,
      image: "opal",
      description: "A glowing, neon orange-red Mexican Fire Opal cabochon. Formed inside ancient volcanic domes, carrying exceptional copper hues to boost romantic charisma and artistic success.",
      specifications: {
        "Carat Weight": "2.20 Carats (2.44 Ratti)",
        "Origin": "Queretaro, Mexico",
        "Color": "Bright Fire Orange",
        "Shape/Cut": "Oval Cabochon",
        "Treatment": "Unheated & Untreated",
        "Clarity": "Translucent Jelly",
        "Planet": "Venus (Shukra)"
      },
      astrology: {
        planet: "Venus",
        rashi: ["Taurus", "Libra"],
        benefits: ["Ignites tremendous creative flame and confidence", "Attracts social love, relationship bonding, and luxury", "Aids in hormonal balance and radiant skin vitality", "Guides entrepreneurs in arts, media, and marketing wins"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "garnet-stone-mozambique",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1fMQKiqLBEgr-_t4gv4k64khpgUkhHvSc=w400-h400-p",
      name: "Deep Red Garnet Stone",
      sku: "PO-GAR-004",
      category: "semi-precious",
      subCategory: "ruby",
      color: "Deep Burgundy Red",
      origin: "Mozambique",
      shape: "Oval Cut",
      weight: "2.10",
      clarity: "Eye Clean",
      treatment: "100% Unheated",
      certificate: "In-House Certified",
      price: 110,
      currency: "USD",
      rating: 4.7,
      reviewsCount: 29,
      image: "ruby",
      description: "A highly lustrous, deep burgundy red Garnet (Hessonites cousin) from Mozambique. Sourced directly to provide strong grounding root-chakra energies.",
      specifications: {
        "Carat Weight": "2.10 Carat (2.33 Ratti)",
        "Origin": "Mozambique",
        "Color": "Deep Wine Red",
        "Shape/Cut": "Oval Cut",
        "Treatment": "Natural Untreated",
        "Clarity": "Eye Clean Table",
        "Planet": "Rahu (Ascending Node)"
      },
      astrology: {
        planet: "Rahu",
        rashi: ["Aquarius"],
        benefits: ["Serves as a powerful substitute for Hessonite (Gomed)", "Grounds active energies and enhances physical stamina", "Boosts circulation, heat, and structural joint health", "Helps clear mental fog and removes structural delays"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "iolite-neeli",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1I9WPF6iE01efMHM3068sYh6NHUNUmTFa=w400-h400-p",
      name: "Vivid Iolite (Neeli)",
      sku: "PO-IOL-005",
      category: "semi-precious",
      subCategory: "blue-sapphire",
      color: "Indigo Violet-Blue",
      origin: "Madagascar",
      shape: "Oval Mixed Cut",
      weight: "2.20",
      clarity: "Eye Clean",
      treatment: "100% Natural",
      certificate: "Laboratory Certified",
      price: 130,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 38,
      image: "blue-sapphire",
      description: "An authentic indigo-colored natural Iolite (Neeli) from Madagascar. Highly pleochroic, shifting from deep violet-blue to gray-yellow under varying angles. The ultimate Saturn substitute.",
      specifications: {
        "Carat Weight": "2.20 Carat (2.44 Ratti)",
        "Origin": "Madagascar",
        "Color": "Indigo Violet-Blue",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "No Indication of Heating",
        "Clarity": "Eye Clean",
        "Planet": "Saturn (Shani)"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius"],
        benefits: ["Exceptional budget substitute for Blue Sapphire (Neelam)", "Clears long-standing financial debts and commercial hurdles", "Enhances psychological intuition and aids in weight management", "Cures sleep disorders and harmonizes crown chakra energy"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "navratna-set",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/12IpMJJYufIH6fdVuEVMipWqV1rrbfmhB=w400-h400-p",
      name: "Authentic Navratna Planetary Talisman",
      sku: "PO-NAV-006",
      category: "semi-precious",
      subCategory: "opal",
      color: "Nine Sacred Colors",
      origin: "Multi-Origin",
      shape: "Mixed Cuts Set",
      weight: "2.30",
      clarity: "Selected Eye Clean",
      treatment: "Natural Mixed Settings",
      certificate: "Talisman Certified",
      price: 650,
      currency: "USD",
      rating: 5.0,
      reviewsCount: 15,
      image: "opal",
      description: "A masterfully selected set of the nine sacred astrological gemstones (Ruby, Pearl, Red Coral, Emerald, Yellow Sapphire, Diamond/Opal, Blue Sapphire, Hessonite, Cat's Eye) representing the nine planets of Vedic cosmology.",
      specifications: {
        "Weight": "Total 2.30 Carats Set",
        "Gemstones Included": "All 9 Vedic Rashi Ratnas",
        "Settings": "Ideal for Navratna Ring / Pendant",
        "Planet": "All Nine Planets (Navagraha)",
        "Zodiac": "Harmonious for All Signs"
      },
      astrology: {
        planet: "Sun",
        rashi: ["All"],
        benefits: ["Balances all nine planetary grids simultaneously", "Brings supreme overall wellness, peace, and abundance", "Removes deep cosmic blocks and negative horoscopic aspects", "Propels status, health, protection, and aura energy"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "opal-dudhiya-pathar",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/19xq4ZKpGnZuIIfWVFl9Snls7JrR9xesW=w400-h400-p",
      name: "Australian Opal (Dudhiya Pathar)",
      sku: "PO-OPL-007",
      category: "semi-precious",
      subCategory: "opal",
      color: "Milky White with Rainbow Play-of-Color",
      origin: "Coober Pedy (Australia)",
      shape: "Oval Cabochon",
      weight: "2.20",
      clarity: "Semi-Translucent",
      treatment: "100% Natural",
      certificate: "IGI Certified",
      price: 220,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 45,
      image: "opal",
      description: "An authentic Australian White Opal (Dudhiya Pathar) from the famous Coober Pedy fields. Houses a stellar 'Play-of-Color' that flashes brilliant red, green, and blue fire under direct light.",
      specifications: {
        "Carat Weight": "2.20 Carat (2.44 Ratti)",
        "Origin": "Coober Pedy, Australia",
        "Color": "White with Rainbow Fire",
        "Shape/Cut": "Oval Cabochon",
        "Treatment": "No Indication of Enhancements",
        "Certification": "IGI Certified",
        "Clarity": "Highly Luminous Translucent",
        "Planet": "Venus (Shukra)"
      },
      astrology: {
        planet: "Venus",
        rashi: ["Taurus", "Libra"],
        benefits: ["Attracts luxury, high-society lifestyle, and financial gains", "Spurs tremendous artistic talent, creativity, and public fame", "Imparts deep romantic harmony and clears marital hurdles", "Improves hormonal health and boosts physical charisma"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "peridot-stone-pakistan",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1yLfenMVXJlMfRCpbLsjTo4La_IV4FB6U=w400-h400-p",
      name: "Natural Peridot Stone",
      sku: "PO-PER-008",
      category: "semi-precious",
      subCategory: "emerald",
      color: "Canary Olive Green",
      origin: "Kashmir Border (Pakistan)",
      shape: "Oval Cut",
      weight: "2.30",
      clarity: "Eye Clean",
      treatment: "100% Unheated",
      certificate: "In-House Certified",
      price: 140,
      currency: "USD",
      rating: 4.7,
      reviewsCount: 22,
      image: "emerald",
      description: "A highly sparkly, olive-green natural Peridot from the Himalayan basins of Pakistan. An outstanding, budget-friendly substitute for Mercury Emerald (Panna).",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Sopat Valley, Pakistan",
        "Color": "Bright Olive Green",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "None (100% Natural)",
        "Clarity": "Eye Clean (Excellent Light Dispersion)",
        "Planet": "Mercury (Budh)"
      },
      astrology: {
        planet: "Mercury",
        rashi: ["Gemini", "Virgo"],
        benefits: ["Excellent affordable substitute for Emerald (Panna)", "Enhances intellect, analytical clarity, and academic skill", "Builds commercial success and handles trade obstacles", "Brings structural calming and handles anxious patterns"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "pitambari-neelam-ceylon",
      name: "Bi-Color Pitambari Neelam",
      sku: "PO-PIT-009",
      category: "precious",
      subCategory: "blue-sapphire",
      color: "Bi-Color Yellow & Blue",
      origin: "Ceylon (Sri Lanka)",
      shape: "Oval Mixed Cut",
      weight: "2.30",
      clarity: "Eye Clean",
      treatment: "100% Unheated",
      certificate: "GRS Certified",
      price: 2450,
      currency: "USD",
      rating: 5.0,
      reviewsCount: 14,
      image: "blue-sapphire",
      description: "An incredibly rare Ceylon bi-color Pitambari Neelam. Exhibits distinct canary yellow and royal blue bands inside the same crystal lattice. Blends the cosmic powers of Jupiter and Saturn.",
      specifications: {
        "Carat Weight": "2.30 Carat (2.55 Ratti)",
        "Origin": "Ceylon, Sri Lanka",
        "Color": "Bicolor Yellow-Blue",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "No Thermal Treatment (Unheated)",
        "Certification": "GRS Lab Certified",
        "Clarity": "Eye Clean Table",
        "Planet": "Saturn & Jupiter",
        "Zodiac": "Capricorn (Makar), Sagittarius (Dhanu)"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius", "Sagittarius", "Pisces"],
        benefits: ["Unifies the extreme fortunes of Pukhraj and Neelam", "Accelerates grand corporate expansions and wealth reserves", "Removes severe financial blocks and family discord", "Provides top administrative acumen and spiritual logic"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "turquoise-persian",
      name: "Authentic Persian Turquoise Stone",
      sku: "PO-TUR-010",
      category: "semi-precious",
      subCategory: "emerald",
      color: "Robin Egg Turquoise Blue",
      origin: "Nishapur (Persia)",
      shape: "Oval Cabochon",
      weight: "2.10",
      clarity: "Opaque",
      treatment: "100% Untreated / No Wax",
      certificate: "Laboratory Certified",
      price: 190,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 26,
      image: "emerald",
      description: "A highly premium, solid robin-egg blue Persian Turquoise (Feroza) from the historic mines of Nishapur. Completely untreated, containing zero artificial color stabilization.",
      specifications: {
        "Carat Weight": "2.10 Carats (2.33 Ratti)",
        "Origin": "Nishapur, Iran (Persia)",
        "Color": "Robin Egg Blue (No Matrix)",
        "Shape/Cut": "Oval Cabochon",
        "Treatment": "100% Pure Natural (No Wax/Dye)",
        "Clarity": "Opaque (Velvet Luster)",
        "Planet": "Jupiter (Guru)"
      },
      astrology: {
        planet: "Jupiter",
        rashi: ["Sagittarius", "Pisces"],
        benefits: ["Serves as a powerful talisman for marital and love fortune", "Shields the wearer from severe accidents and negative spells", "Imparts deep spiritual intellect and handles stress", "Brings professional fame, stability, and wealth"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "white-coral-italian",
      name: "Vedic White Coral (Moonga)",
      sku: "PO-COR-011",
      category: "semi-precious",
      subCategory: "red-coral",
      color: "Pure Chalk White",
      origin: "Sardinia (Italy)",
      shape: "Oval Cabochon",
      weight: "2.00",
      clarity: "Opaque",
      treatment: "100% Natural",
      certificate: "In-House Certified",
      price: 120,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 16,
      image: "red-coral",
      description: "A pristine, pure white natural Italian Coral (Safed Moonga) from Sardinia. Selected with a smooth, spot-free surface to enhance planetary Mars and Venus balances.",
      specifications: {
        "Carat Weight": "2.00 Carats (2.22 Ratti)",
        "Origin": "Sardinia, Italy",
        "Color": "Pure White",
        "Shape/Cut": "Oval Cabochon",
        "Treatment": "Natural Untreated Coral",
        "Clarity": "Smooth Opaque",
        "Planet": "Mars & Venus"
      },
      astrology: {
        planet: "Mars",
        rashi: ["Aries", "Scorpio", "Taurus", "Libra"],
        benefits: ["Reduces general short-temper, anger, and anxiety", "Attracts financial gains and controls planetary blocks", "Exceptional for respiratory, metabolic, and bone wellness", "Keeps evil eyes and emotional mood shifts away"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "yellow-topaz-stone",
      name: "Natural Yellow Topaz Stone",
      sku: "PO-TOP-012",
      category: "semi-precious",
      subCategory: "yellow-sapphire",
      color: "Canary Golden Yellow",
      origin: "Ouro Preto (Brazil)",
      shape: "Oval Cushion Cut",
      weight: "2.30",
      clarity: "Eye Clean Table",
      treatment: "100% Unheated",
      certificate: "Laboratory Certified",
      price: 210,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 19,
      image: "yellow-sapphire",
      description: "An authentic golden yellow Brazilian Topaz. Exhibits outstanding transparency and a highly energetic canary shine. A brilliant astrological channeler.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Ouro Preto, Brazil",
        "Color": "Canary Golden Yellow",
        "Shape/Cut": "Oval Cushion Cut",
        "Treatment": "100% Natural Unheated",
        "Certification": "Laboratory Certified Natural",
        "Clarity": "Eye Clean",
        "Planet": "Jupiter (Guru)"
      },
      astrology: {
        planet: "Jupiter",
        rashi: ["Sagittarius", "Pisces"],
        benefits: ["Premium substitute for Yellow Sapphire (Pukhraj)", "Provides top administrative wisdom, focus, and fame", "Brings business expansions and clears legal hurdles", "Imparts deep mental calm and balances digestive organs"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "zircon-stone-jarkan",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1tdGsadXqEwjFmw2ygZkyDNrd96V06an-=w400-h400-p",
      name: "Sparkly White Zircon (Jarkan)",
      sku: "PO-ZIR-013",
      category: "semi-precious",
      subCategory: "opal",
      color: "Colorless Sparkly White",
      origin: "Pailin (Cambodia)",
      shape: "Round Brilliant Cut",
      weight: "2.40",
      clarity: "Flawless",
      treatment: "100% Natural",
      certificate: "Laboratory Certified",
      price: 160,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 33,
      image: "opal",
      description: "A highly sparkly white Zircon (Jarkan) from Pailin, Cambodia. Possesses an exceptionally high refractive index and double refraction, rivaling white diamonds in fire and astrological beauty.",
      specifications: {
        "Carat Weight": "2.40 Carat (2.66 Ratti)",
        "Origin": "Pailin, Cambodia",
        "Color": "Sparkling Colorless White",
        "Shape/Cut": "Round Brilliant Cut",
        "Treatment": "None (100% Pure Zircon)",
        "Clarity": "Flawless",
        "Planet": "Venus (Shukra)"
      },
      astrology: {
        planet: "Venus",
        rashi: ["Taurus", "Libra"],
        benefits: ["Budget substitute for real diamonds", "Attracts romantic charm, marital bliss, and luxury wins", "Sharpen creative ideas and builds corporate status", "Regulates hormonal balance and aids skin glow"]
      },
      faqs: [],
      reviews: []
    },

    // === ZODIAC STONES ===
    {
      id: "blue-sapphire-zodiac",
      name: "Natural Blue Sapphire (Neelam)",
      sku: "ZO-SAP-001",
      category: "precious",
      subCategory: "blue-sapphire",
      color: "Royal Velvet Blue",
      origin: "Ceylon (Sri Lanka)",
      shape: "Oval Mixed Cut",
      weight: "2.30",
      clarity: "Eye Clean Table",
      treatment: "100% Unheated",
      certificate: "GRS Certified",
      price: 1950,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 48,
      image: "blue-sapphire",
      description: "An authentic Ratnapura Ceylon Blue Sapphire (Neelam). Hand-selected for Capricorn and Aquarius ascendants seeking rapid astrological breakthrough and wealth accumulation.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Ceylon, Sri Lanka",
        "Color": "Deep Velvet Blue",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "No Indication of Heating",
        "Certification": "GRS Certified",
        "Clarity": "Eye Clean",
        "Planet": "Saturn (Shani)"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius"],
        benefits: ["Triggers swift professional opportunities and gains", "Clears longstanding confusion and sharpens focus", "Shields from dark spells, accidents, and enemies", "Aligns solar and throat chakra balances"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "cats-eye-zodiac",
      name: "Chatoyant Cat's Eye (Lehsuniya)",
      sku: "ZO-CAT-002",
      category: "semi-precious",
      subCategory: "opal",
      color: "Chatoyant Greenish-Yellow",
      origin: "Ceylon (Sri Lanka)",
      shape: "Oval Cabochon",
      weight: "2.10",
      clarity: "Sharp Eye",
      treatment: "100% Untreated",
      certificate: "In-House Certified",
      price: 280,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 22,
      image: "opal",
      description: "A highly chatoyant, natural Chrysoberyl Cat's Eye (Lehsuniya Pathar) from Sri Lanka. Features a highly defined, razor-sharp white band that glides smoothly across the dome under single-source illumination.",
      specifications: {
        "Carat Weight": "2.10 Carats (2.33 Ratti)",
        "Origin": "Ceylon, Sri Lanka",
        "Color": "Greenish-Yellow with White Eye",
        "Shape/Cut": "Oval Cabochon",
        "Treatment": "Untreated & Unheated",
        "Clarity": "Translucent Opaque",
        "Planet": "Ketu (South Node)"
      },
      astrology: {
        planet: "Ketu",
        rashi: ["All"],
        benefits: ["Wards off severe evil spells and business rivals", "Brings extreme fortune in trade and speculative games", "Aids in strong bone, skin, and psychological wellness", "Clears deep-seated anxiety and karmic delays"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "emerald-zodiac-panna",
      name: "Natural Emerald (Panna Stone)",
      sku: "ZO-EME-003",
      category: "precious",
      subCategory: "emerald",
      color: "Luminous Bright Green",
      origin: "Zambia",
      shape: "Emerald Octagon Cut",
      weight: "2.30",
      clarity: "Minor Oil Only",
      treatment: "Standard Light Oil Only",
      certificate: "GIA Certified",
      price: 1850,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 31,
      image: "emerald",
      description: "A textbook bright green Zambian Emerald (Panna). Ideal for Gemini and Virgo ascendants, hand-selected to provide the perfect balance of commercial intelligence and astrological speed.",
      specifications: {
        "Carat Weight": "2.30 Carat (2.55 Ratti)",
        "Origin": "Zambia",
        "Color": "Vivid Green",
        "Shape/Cut": "Emerald Octagon Cut",
        "Treatment": "Standard Light Clarification Only",
        "Certification": "GIA Certified",
        "Clarity": "Highly Transparent",
        "Planet": "Mercury (Budh)"
      },
      astrology: {
        planet: "Mercury",
        rashi: ["Gemini", "Virgo"],
        benefits: ["Fuels business profits, corporate wins, and math success", "Sharpen memory, vocabulary, and sales pitch skills", "Imparts deep respiratory, speech, and immune strength", "Acts as an exceptional charm for study success"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "gomed-hessonite",
      name: "Vedic Gomed Stone (Hessonite)",
      sku: "ZO-GOM-004",
      category: "semi-precious",
      subCategory: "red-coral",
      color: "Canary Honey Brown",
      origin: "Ceylon (Sri Lanka)",
      shape: "Oval Mixed Cut",
      weight: "2.10",
      clarity: "Eye Clean Table",
      treatment: "100% Untreated",
      certificate: "Laboratory Certified",
      price: 180,
      currency: "USD",
      rating: 4.7,
      reviewsCount: 29,
      image: "red-coral",
      description: "A highly brilliant, honey-brown natural Hessonite (Gomed) from Sri Lanka. Features a rich, deep-saturated color resembling forest honey, selected to clear the shadow planetary influences of Rahu.",
      specifications: {
        "Carat Weight": "2.10 Carat (2.33 Ratti)",
        "Origin": "Ceylon, Sri Lanka",
        "Color": "Honey-Brown",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "None (100% Pure Gomed)",
        "Clarity": "Eye Clean Table",
        "Planet": "Rahu (North Node)"
      },
      astrology: {
        planet: "Rahu",
        rashi: ["Aquarius"],
        benefits: ["Clears mental doubts, heavy anxiety, and mood swings", "Brings sudden lottery success, wealth, and trade gains", "Speeds up delayed litigation, visas, and legal disputes", "Balances stomach systems, nerve lines, and skin issues"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "pearl-moti",
      name: "Natural Pearl Stone (Moti)",
      sku: "ZO-PRL-005",
      category: "semi-precious",
      subCategory: "opal",
      color: "Silvery White",
      origin: "South Sea",
      shape: "Perfect Round",
      weight: "2.10",
      clarity: "Nacre Luminous Flawless",
      treatment: "100% Untreated",
      certificate: "Laboratory Certified",
      price: 260,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 37,
      image: "opal",
      description: "An incredibly beautiful, high-luster perfect round South Sea Pearl (Moti). Sourced from pure saltwater oysters, possessing a thick nacre that reflects planetary Moon energies for mental calm.",
      specifications: {
        "Carat Weight": "2.10 Carats (2.33 Ratti)",
        "Origin": "South Sea",
        "Color": "Silvery White",
        "Shape/Cut": "Round Spherical",
        "Treatment": "Natural Untreated Pearl",
        "Clarity": "Flawless Nacre Surface",
        "Planet": "Moon (Chandra)"
      },
      astrology: {
        planet: "Moon",
        rashi: ["Cancer"],
        benefits: ["Calms the hot-temper, severe anxiety, and panic loops", "Imparts deep emotional stability, family joy, and focus", "Regulates biological water balances, blood pressure, and sleep", "Acts as the ultimate charm for artists, mothers, and writers"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "red-coral-moonga",
      name: "Vedic Red Coral (Moonga Stone)",
      sku: "ZO-COR-006",
      category: "semi-precious",
      subCategory: "red-coral",
      color: "Ox-Blood Crimson Red",
      origin: "Sardinia (Italy)",
      shape: "Oval Cabochon",
      weight: "2.10",
      clarity: "Opaque Smooth",
      treatment: "100% Natural",
      certificate: "GIA Certified",
      price: 190,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 41,
      image: "red-coral",
      description: "A textbook ox-blood crimson red Italian Coral (Moonga) from Sardinia. Sourced with a smooth, notch-free surface to enhance physical Mars alignment.",
      specifications: {
        "Carat Weight": "2.10 Carat (2.33 Ratti)",
        "Origin": "Sardinia, Italy",
        "Color": "Ox-Blood Deep Red",
        "Shape/Cut": "Oval Cabochon",
        "Treatment": "No Indication of Wax/Dye",
        "Certification": "GIA Certified",
        "Clarity": "Smooth Lustrous Opaque",
        "Planet": "Mars (Mangal)"
      },
      astrology: {
        planet: "Mars",
        rashi: ["Aries", "Scorpio"],
        benefits: ["Reduces severe lethargy, fear, and controls Manglik delays", "Ignites tremendous corporate ambitions, stamina, and drive", "Acts as the ultimate healer for muscles, bones, and blood", "Imparts a protective shield against accidents and evil vibes"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "ruby-zodiac-manik",
      name: "Natural Ruby Stone (Manik Stone)",
      sku: "ZO-RUB-007",
      category: "precious",
      subCategory: "ruby",
      color: "Crimson Pigeon Blood Red",
      origin: "Mogok (Burma)",
      shape: "Oval Mixed Cut",
      weight: "2.20",
      clarity: "Slightly Included Table Clean",
      treatment: "100% Unheated",
      certificate: "GRS Certified",
      price: 3600,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 34,
      image: "ruby",
      description: "An outstanding Mogok Burmese Ruby (Manik). Ideal for Leo ascendants, hand-selected to provide the perfect balance of confidence, solar energy, and social status.",
      specifications: {
        "Carat Weight": "2.20 Carat (2.44 Ratti)",
        "Origin": "Mogok, Burma",
        "Color": "Pigeon Blood Red",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "No Heat / 100% Untreated",
        "Certification": "GRS Certified",
        "Clarity": "Luminous Transparent",
        "Planet": "Sun (Surya)"
      },
      astrology: {
        planet: "Sun",
        rashi: ["Leo"],
        benefits: ["Brings immense social authority, willpower, and command", "Clears emotional blockages, lethargy, and stage-fright", "Imparts highly robust cardio and blood circulation strength", "Guides elite corporate, state, and political careers to win"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "white-sapphire-zodiac",
      name: "Natural White Sapphire (Safed Pukhraj)",
      sku: "ZO-SAP-008",
      category: "precious",
      subCategory: "yellow-sapphire",
      color: "Colorless Sparkly White",
      origin: "Ceylon (Sri Lanka)",
      shape: "Oval Mixed Cut",
      weight: "2.30",
      clarity: "Eye Clean",
      treatment: "100% Unheated",
      certificate: "GIA Certified",
      price: 2150,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 15,
      image: "yellow-sapphire",
      description: "A GIA-certified, highly sparkly colorless natural White Sapphire (Safed Pukhraj) from Ceylon. Possesses outstanding brilliance and fire, serving as the ultimate Venus planet channeler.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Ceylon, Sri Lanka",
        "Color": "Colorless White",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "Unheated & Untreated",
        "Certification": "GIA Certified",
        "Clarity": "Eye Clean Table",
        "Planet": "Venus (Shukra)"
      },
      astrology: {
        planet: "Venus",
        rashi: ["Taurus", "Libra"],
        benefits: ["Serves as a powerful, premium substitute for real diamonds", "Attracts romantic charm, marital bliss, and luxury wealth", "Boosts creative vision, artistry, and public reputation", "Improves hormonal health and balances metabolic functions"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "yellow-sapphire-zodiac",
      name: "Natural Yellow Sapphire (Pukhraj Stone)",
      sku: "ZO-SAP-009",
      category: "precious",
      subCategory: "yellow-sapphire",
      color: "Canary Canary Yellow",
      origin: "Ceylon (Sri Lanka)",
      shape: "Oval Mixed Cut",
      weight: "2.40",
      clarity: "Eye Clean Table",
      treatment: "100% Unheated",
      certificate: "GIA Certified",
      price: 1850,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 52,
      image: "yellow-sapphire",
      description: "An authentic, highly brilliant canary yellow Ceylon Sapphire (Pukhraj Stone). Ideal for Sagittarius and Pisces ascendants, selected to provide high academic wins, wisdom, and massive fortunes.",
      specifications: {
        "Carat Weight": "2.40 Carat (2.66 Ratti)",
        "Origin": "Ceylon, Sri Lanka",
        "Color": "Canary Yellow",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "No Indication of Heating",
        "Certification": "GIA Certified",
        "Clarity": "Eye Clean Table",
        "Planet": "Jupiter (Guru)"
      },
      astrology: {
        planet: "Jupiter",
        rashi: ["Sagittarius", "Pisces"],
        benefits: ["Brings immense wealth, grand business fortune, and status", "Dramatically sharpens intellectual power and spiritual vision", "Guards from family discords, legal loops, and child-rearing blocks", "Boosts liver health, blood pressure balance, and metabolic health"]
      },
      faqs: [],
      reviews: []
    },

    // === OTHER GEMSTONES ===
    {
      id: "amber-baltic",
      name: "Baltic Amber fossil",
      sku: "OT-AMB-001",
      category: "semi-precious",
      subCategory: "yellow-sapphire",
      color: "Honey Gold",
      origin: "Baltic",
      shape: "Oval Cabochon",
      weight: "2.40",
      clarity: "Clear with organic inclusions",
      treatment: "100% Untreated",
      certificate: "In-House Certified",
      price: 130,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 15,
      image: "yellow-sapphire",
      description: "A glowing Baltic Amber cabochon carrying historic organic pine fossil inclusions. Grounding, calming, and highly therapeutic.",
      specifications: {
        "Carat Weight": "2.40 Carat (2.66 Ratti)",
        "Origin": "Baltic Region",
        "Color": "Honey Orange-Yellow",
        "Shape/Cut": "Oval Cabochon",
        "Treatment": "Natural Fossil",
        "Clarity": "Transparent to Translucent",
        "Planet": "Jupiter"
      },
      astrology: {
        planet: "Jupiter",
        rashi: ["Sagittarius", "Pisces"],
        benefits: ["Imparts highly robust physical vitality and warmth", "Grounds active nervous energies and anxiety loops", "Triggers deep cellular healing and bone strength", "Balances solar plexus and throat energy points"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "ametrine-bolivian",
      name: "Bicolor Bolivian Ametrine",
      sku: "OT-AMR-002",
      category: "semi-precious",
      subCategory: "amethyst",
      color: "Bicolor Purple-Yellow",
      origin: "Anahi (Bolivia)",
      shape: "Emerald Octagon Cut",
      weight: "2.20",
      clarity: "Flawless",
      treatment: "100% Unheated",
      certificate: "In-House Certified",
      price: 160,
      currency: "USD",
      rating: 4.7,
      reviewsCount: 19,
      image: "amethyst",
      description: "A highly dramatic, bi-color Ametrine from the Anahi mines of Bolivia. Merges golden Citrine and purple Amethyst in a single crystalline structure.",
      specifications: {
        "Carat Weight": "2.20 Carats (2.44 Ratti)",
        "Origin": "Anahi Mine, Bolivia",
        "Color": "Bi-Color Violet & Golden",
        "Shape/Cut": "Emerald Octagon Cut",
        "Treatment": "None (100% Natural)",
        "Clarity": "Flawless",
        "Planet": "Jupiter & Saturn"
      },
      astrology: {
        planet: "Jupiter",
        rashi: ["Sagittarius", "Pisces", "Capricorn", "Aquarius"],
        benefits: ["Combines the creative flame of Citrine and peaceful calm of Amethyst", "Clears blockages between physical goals and spiritual wisdom", "Aids in strong metabolic balance and liver function", "Acts as the ultimate positive vibe and self-worth builder"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "aquamarine-beruj",
      name: "Natural Aquamarine Stone (Beruj)",
      sku: "OT-AQM-003",
      category: "semi-precious",
      subCategory: "blue-sapphire",
      color: "Ocean Blue-Green",
      origin: "Brazil",
      shape: "Oval Cushion Cut",
      weight: "2.40",
      clarity: "Eye Clean Table",
      treatment: "100% Unheated",
      certificate: "In-House Certified",
      price: 210,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 23,
      image: "blue-sapphire",
      description: "A highly brilliant, sky-blue natural Aquamarine (Beruj Pathar) from Brazil. Sourced to provide strong third-eye and throat chakra channels.",
      specifications: {
        "Carat Weight": "2.40 Carats (2.66 Ratti)",
        "Origin": "Minas Gerais, Brazil",
        "Color": "Sky Blue",
        "Shape/Cut": "Oval Cushion Cut",
        "Treatment": "Natural Unheated",
        "Clarity": "Eye Clean Table",
        "Planet": "Saturn (Shani)"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius"],
        benefits: ["Strong budget substitute for Blue Sapphire (Neelam)", "Relieves mental stress, throat issues, and speech blockages", "Guides sea-travelers and triggers deep intuition", "Brings business expansions and clears karmic cycles"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "blue-topaz-swiss",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1afzumRQMnRaD3xKdSS4Why3AuTVlBaTB=w400-h400-p",
      name: "Swiss Blue Topaz",
      sku: "OT-TOP-004",
      category: "semi-precious",
      subCategory: "blue-sapphire",
      color: "Vibrant Swiss Blue",
      origin: "Brazil",
      shape: "Oval Cut",
      weight: "2.30",
      clarity: "Flawless",
      treatment: "Standard Light Heat Only",
      certificate: "In-House Certified",
      price: 130,
      currency: "USD",
      rating: 4.7,
      reviewsCount: 30,
      image: "blue-sapphire",
      description: "A highly sparkling Swiss Blue Topaz from Brazil. Excellent clarity and cut to serve as a strong budget Saturn helper.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Brazil",
        "Color": "Vibrant Swiss Blue",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "Standard Light Thermal Heat Only",
        "Clarity": "Flawless Table",
        "Planet": "Saturn"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius"],
        benefits: ["Aids in removing communication limits and vocal blocks", "Triggers deep logical thinking and keeps distress away", "Brings financial stability and commercial clarity", "Aligns throat and crown chakra energy points"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "blue-zircon-pailin",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1x8SfdvAP-ECMQGRTWndx4pqci3Bff5a_=w400-h400-p",
      name: "Vibrant Cambodian Blue Zircon",
      sku: "OT-ZIR-005",
      category: "semi-precious",
      subCategory: "opal",
      color: "Electric Teal Blue",
      origin: "Pailin (Cambodia)",
      shape: "Oval Cushion Cut",
      weight: "2.40",
      clarity: "Eye Clean Table",
      treatment: "Standard Heat Only",
      certificate: "In-House Certified",
      price: 170,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 20,
      image: "opal",
      description: "A highly brilliant, electric teal blue Zircon from Cambodia. Extremely sparky due to double refraction, serving as a powerful Venus and Mercury balancer.",
      specifications: {
        "Carat Weight": "2.40 Carat (2.66 Ratti)",
        "Origin": "Pailin, Cambodia",
        "Color": "Electric Teal Blue",
        "Shape/Cut": "Oval Cushion Cut",
        "Treatment": "Standard Low Heat Only",
        "Clarity": "Eye Clean Table",
        "Planet": "Venus & Mercury"
      },
      astrology: {
        planet: "Venus",
        rashi: ["Taurus", "Libra", "Gemini", "Virgo"],
        benefits: ["Attracts massive romantic fire, marital harmony, and luck", "Sharpens commercial vision and academic creativity", "Triggers metabolic balance and aids skin glow", "Shields from anxious thoughts and psychological blocks"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "kyanite-nepal",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1zRb7effDdZxM672NHJCON4SR22L7GYUV=w400-h400-p",
      name: "Deep Indigo Nepal Kyanite",
      sku: "OT-KYN-006",
      category: "semi-precious",
      subCategory: "blue-sapphire",
      color: "Deep Sapphire Blue",
      origin: "Himalayas (Nepal)",
      shape: "Oval Cut",
      weight: "2.20",
      clarity: "Slightly Included Table Clean",
      treatment: "100% Natural",
      certificate: "In-House Certified",
      price: 110,
      currency: "USD",
      rating: 4.6,
      reviewsCount: 12,
      image: "blue-sapphire",
      description: "A deep sapphire blue natural Kyanite from the high Himalayan beds of Nepal. Self-cleansing, grounding, and spiritually powerful.",
      specifications: {
        "Carat Weight": "2.20 Carats (2.44 Ratti)",
        "Origin": "Himalayas, Nepal",
        "Color": "Deep Sapphire Blue",
        "Shape/Cut": "Oval Mixed Cut",
        "Treatment": "None (100% Natural)",
        "Clarity": "Highly Translucent",
        "Planet": "Saturn"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius"],
        benefits: ["Excellent affordable substitute for Blue Sapphire (Neelam)", "Instantly aligns and balances all throat and mind chakra points", "Enhances communication, public speech, and logical vision", "Dispels mental doubts and removes corporate barriers"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "lapis-lazuli-afghan",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/14gH7lxgQOawprtSBtNHeZe4wUBtBTfqS=w400-h400-p",
      name: "Royal Lapis Lazuli",
      sku: "OT-LAP-007",
      category: "semi-precious",
      subCategory: "blue-sapphire",
      color: "Royal Blue with Pyrite Flecks",
      origin: "Badakhshan (Afghanistan)",
      shape: "Oval Flat Cabochon",
      weight: "3.00",
      clarity: "Opaque",
      treatment: "100% Natural / Unwaxed",
      certificate: "In-House Certified",
      price: 80,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 51,
      image: "blue-sapphire",
      description: "A royal blue Lapis Lazuli flat cabochon from Badakhshan, Afghanistan. Contains high-quality gold pyrite speckles, providing deep intellectual Saturn energy.",
      specifications: {
        "Carat Weight": "3.00 Carats (3.33 Ratti)",
        "Origin": "Badakhshan, Afghanistan",
        "Color": "Deep Royal Blue with Golden Pyrite",
        "Shape/Cut": "Oval Cabochon",
        "Treatment": "Natural Unwaxed",
        "Clarity": "Smooth Opaque",
        "Planet": "Saturn & Jupiter"
      },
      astrology: {
        planet: "Saturn",
        rashi: ["Capricorn", "Aquarius", "Sagittarius"],
        benefits: ["Prime substitute for Blue Sapphire (Neelam)", "Stimulates throat, third-eye, and crown chakra points", "Brings deep administrative skills and financial growth", "Enhances memory, visual perception, and logical vision"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "moldavite-czech",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1kWqFsICr2ODTjjxtL7djF5fqO8uj-Ecx=w400-h400-p",
      name: "Sacred Forest Green Moldavite",
      sku: "OT-MLD-008",
      category: "semi-precious",
      subCategory: "emerald",
      color: "Forest Green with Tektite texture",
      origin: "Moldau River (Czech)",
      shape: "Rough Cut Cabochon",
      weight: "3.00",
      clarity: "Translucent with bubbles",
      treatment: "100% Natural Tektite",
      certificate: "Space Certified",
      price: 850,
      currency: "USD",
      rating: 5.0,
      reviewsCount: 9,
      image: "emerald",
      description: "A highly rare, extraterrestrial forest green Moldavite cabochon from the Czech Republic. Formed from a meteorite impact 15 million years ago. Incredible spiritual catalyst.",
      specifications: {
        "Carat Weight": "3.00 Carats (3.33 Ratti)",
        "Origin": "Moldau River Valley, Czech Republic",
        "Color": "Forest Green",
        "Shape/Cut": "Freeform Cabochon",
        "Treatment": "Natural Tektite Glass",
        "Clarity": "Translucent with classic lechatelierite lines",
        "Planet": "Rahu & Ketu"
      },
      astrology: {
        planet: "Rahu",
        rashi: ["All"],
        benefits: ["Triggers swift, massive life transformations and updates", "Balances high energy blocks and triggers deep heart chakra flow", "Acts as the ultimate cosmic protection talisman", "Propels status, health, and aura energy reserves"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "moonstone-sri-lanka",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1h025nTvUt4vXm-ryUpWtbrPL3Z3YlW8-=w400-h400-p",
      name: "Pearly Adularescent Moonstone",
      sku: "OT-MON-009",
      category: "semi-precious",
      subCategory: "opal",
      color: "Pearly White with Blue Sheen",
      origin: "Meetiyagoda (Sri Lanka)",
      shape: "Oval Cabochon",
      weight: "2.10",
      clarity: "Highly Translucent",
      treatment: "100% Natural",
      certificate: "In-House Certified",
      price: 120,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 14,
      image: "opal",
      description: "A gorgeous Ceylon Moonstone exhibiting the classic pearly white body and shimmering adularescent blue sheen. Highly recommended for emotional balance and moon energies.",
      specifications: {
        "Carat Weight": "2.10 Carat (2.33 Ratti)",
        "Origin": "Meetiyagoda, Sri Lanka",
        "Color": "Pearly White with Blue Sheen",
        "Shape/Cut": "Oval Cabochon",
        "Treatment": "Natural Untreated",
        "Clarity": "Highly Translucent",
        "Planet": "Moon (Chandra)"
      },
      astrology: {
        planet: "Moon",
        rashi: ["Cancer"],
        benefits: ["Prime affordable substitute for Pearl (Moti)", "Calms high short-temper, severe anxiety, and panic loops", "Imparts deep emotional stability, family joy, and focus", "Regulates biological water balances, blood pressure, and sleep"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "spinel-burmese",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1Xj3iRFEQNLsRzyXooZrjlXVoAIEMoSpG=w400-h400-p",
      name: "Flame Red Burmese Spinel",
      sku: "OT-SPI-010",
      category: "semi-precious",
      subCategory: "ruby",
      color: "Flame Crimson Red",
      origin: "Mogok (Burma)",
      shape: "Oval Cushion Cut",
      weight: "2.30",
      clarity: "Eye Clean",
      treatment: "100% Unheated",
      certificate: "In-House Certified",
      price: 280,
      currency: "USD",
      rating: 4.9,
      reviewsCount: 11,
      image: "ruby",
      description: "A brilliant flame red Spinel from the Mogok mines of Burma. Known as the 'great imposter' of history, providing identical visual fire and astrological Sun alignment to Burmese Rubies.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Mogok, Burma",
        "Color": "Flame Red",
        "Shape/Cut": "Oval Cushion Cut",
        "Treatment": "Unheated & Untreated",
        "Clarity": "Eye Clean Table",
        "Planet": "Sun & Saturn"
      },
      astrology: {
        planet: "Sun",
        rashi: ["Leo", "Capricorn"],
        benefits: ["Excellent affordable substitute for Ruby (Manik)", "Triggers leadership authority, willpower, and command", "Clears emotional blockages, lethargy, and stage-fright", "Imparts highly robust cardio and blood circulation strength"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "star-ruby-surya",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/1wxLK-0lLRR2poHW0a0pNHnXEnfgmwSwU=w400-h400-p",
      name: "Asteriated Star Ruby (Surya Kant)",
      sku: "OT-SRB-011",
      category: "semi-precious",
      subCategory: "ruby",
      color: "Deep Purplish Red with 6-Ray Star",
      origin: "India",
      shape: "Oval Cabochon",
      weight: "2.30",
      clarity: "Opaque with sharp star",
      treatment: "100% Natural",
      certificate: "Laboratory Certified",
      price: 340,
      currency: "USD",
      rating: 4.8,
      reviewsCount: 16,
      image: "ruby",
      description: "A highly mystical natural Star Ruby cabochon from India. Features a beautifully defined, sharp 6-ray star that floats across the crimson surface under direct sun or torchlight. High solar power.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Karnatak, India",
        "Color": "Purplish Red with 6-Ray Star",
        "Shape/Cut": "Oval Cabochon",
        "Treatment": "No Indication of Heat/Diffusion",
        "Clarity": "Opaque (Asteriated)",
        "Planet": "Sun (Surya)"
      },
      astrology: {
        planet: "Sun",
        rashi: ["Leo"],
        benefits: ["Connects with deep ancestral and solar protection grids", "Fuels supreme self-worth, courage, and administrative status", "Reduces physical lethargy and balances cardiac meridians", "Guides elite corporate, state, and political careers to win"]
      },
      faqs: [],
      reviews: []
    },
    {
      id: "tourmaline-multicolor",
      driveImage: "https://lh3.googleusercontent.com/u/0/d/19ydtdY9lZfV6eR49Lpi2vfRF4ytGOfmF=w400-h400-p",
      name: "Bi-Color Tourmaline",
      sku: "OT-TOR-012",
      category: "semi-precious",
      subCategory: "emerald",
      color: "Bi-Color Pink & Green",
      origin: "Brazil",
      shape: "Emerald Octagon Cut",
      weight: "2.30",
      clarity: "Eye Clean",
      treatment: "100% Natural Unheated",
      certificate: "In-House Certified",
      price: 190,
      currency: "USD",
      rating: 4.7,
      reviewsCount: 18,
      image: "emerald",
      description: "A beautiful bi-color watermelon Tourmaline. Exhibits distinct green and pink segments inside the same crystal lattice. Combines Mercury and Venus planet alignments.",
      specifications: {
        "Carat Weight": "2.30 Carats (2.55 Ratti)",
        "Origin": "Brazil",
        "Color": "Bicolor Pink-Green",
        "Shape/Cut": "Emerald Octagon Cut",
        "Treatment": "Natural Unheated",
        "Clarity": "Eye Clean Table",
        "Planet": "Mercury & Venus"
      },
      astrology: {
        planet: "Mercury",
        rashi: ["Gemini", "Virgo", "Taurus", "Libra"],
        benefits: ["Brings deep-level business updates and relationship stability", "Balances intellectual ideas and artistic pursuits", "Aids in skin glow and boosts commercial communications", "Keeps evil eyes and emotional mood shifts away"]
      },
      faqs: [],
      reviews: []
    }
  ],

  // Auxiliary Cosmology Tables
  astrologyGuides: {
    planets: {
      "Sun": { stone: "Ruby (Manik)", rashi: "Leo", mantra: "Om Hram Hreem Hroum Sah Suryaya Namah" },
      "Moon": { stone: "Pearl (Moti)", rashi: "Cancer", mantra: "Om Shram Shreem Shroum Sah Chandraya Namah" },
      "Mars": { stone: "Red Coral (Moonga)", rashi: "Aries & Scorpio", mantra: "Om Kram Kreem Kroum Sah Bhaumaya Namah" },
      "Mercury": { stone: "Emerald (Panna)", rashi: "Gemini & Virgo", mantra: "Om Bram Breem Broum Sah Budhaya Namah" },
      "Jupiter": { stone: "Yellow Sapphire (Pukhraj)", rashi: "Sagittarius & Pisces", mantra: "Om Gram Greem Groum Sah Guruve Namah" },
      "Venus": { stone: "Opal / Diamond / White Sapphire", rashi: "Taurus & Libra", mantra: "Om Dram Dreem Droum Sah Shukraya Namah" },
      "Saturn": { stone: "Blue Sapphire (Neelam)", rashi: "Capricorn & Aquarius", mantra: "Om Pram Preem Proum Sah Shanishcharaya Namah" }
    },
    zodiacs: {
      "Aries": { englishName: "Aries", rashiName: "Mesh", lord: "Mars", stone: "Red Coral (Moonga)" },
      "Taurus": { englishName: "Taurus", rashiName: "Vrish", lord: "Venus", stone: "Opal / White Sapphire" },
      "Gemini": { englishName: "Gemini", rashiName: "Mithun", lord: "Mercury", stone: "Emerald (Panna)" },
      "Cancer": { englishName: "Cancer", rashiName: "Kark", lord: "Moon", stone: "Pearl (Moti)" },
      "Leo": { englishName: "Leo", rashiName: "Simha", lord: "Sun", stone: "Ruby (Manik)" },
      "Virgo": { englishName: "Virgo", rashiName: "Kanya", lord: "Mercury", stone: "Emerald (Panna)" },
      "Libra": { englishName: "Libra", rashiName: "Tula", lord: "Venus", stone: "Opal / White Sapphire" },
      "Scorpio": { englishName: "Scorpio", rashiName: "Vrishchik", lord: "Mars", stone: "Red Coral (Moonga)" },
      "Sagittarius": { englishName: "Sagittarius", rashiName: "Dhanu", lord: "Jupiter", stone: "Yellow Sapphire (Pukhraj)" },
      "Capricorn": { englishName: "Capricorn", rashiName: "Makar", lord: "Saturn", stone: "Blue Sapphire (Neelam)" },
      "Aquarius": { englishName: "Aquarius", rashiName: "Kumbh", lord: "Saturn", stone: "Blue Sapphire (Neelam)" },
      "Pisces": { englishName: "Pisces", rashiName: "Meen", lord: "Jupiter", stone: "Yellow Sapphire (Pukhraj)" }
    }
  },

  educationalEncyclopedia: [
    {
      title: "Gemstone Quality Buying Guide (The 4 Cs)",
      slug: "buying-guide-4cs",
      category: "buying-guide",
      summary: "Understand the core variables that define gemstone value: Color, Clarity, Cut, and Carat Weight, tailored for colored astrological stones.",
      content: `### Demystifying Colored Gemstone Valuation
Unlike white diamonds, colored gemstones are valued primarily on their unique color hue, tone, and saturation. When selecting an astrological gemstone, authenticity and purity reign supreme.

#### 1. Color (The Most Crucial Factor)
Color is divided into three components:
- **Hue**: The primary color family (e.g. Red, Blue, Green).
- **Tone**: The relative lightness or darkness (Medium-dark is usually best).
- **Saturation**: The strength or purity of the color (Vibrant, vivid tones hold high value).

#### 2. Clarity
While diamonds are expected to be flawless, colored stones are naturally included. Astrological gems must be relatively clear so light can pass cleanly and reach your skin. Avoid fractures or dark spots centered on the table facet.

#### 3. Cut
An expert cut maximizes fire, brilliance, and color intensity. For astrological utility, the base of the stone should remain unpolished and flat, facilitating comfortable skin contact when set in a ring or pendant.

#### 4. Carat Weight (Ratti)
In Vedic science, gemstone weight is calculated in Ratti. As a rule of thumb, wear 1 Ratti of gemstone weight per 10-12 kilograms of your body weight.`
    }
  ],

  blogs: [
    {
      title: "Why Sri Lankan Ceylon Sapphires are the Pinnacle of Quality",
      slug: "why-ceylon-sapphires-pinnacle",
      author: "Acharya Shastri",
      date: "May 25, 2026",
      excerpt: "Explore the legendary geology of Sri Lanka and why unheated Ceylon Sapphires are the absolute favorites for astrology and investments alike.",
      image: "blue-sapphire"
    },
    {
      title: "Manglik Dosha and the Therapeutic Powers of Italian Red Coral",
      slug: "manglik-dosha-italian-red-coral",
      author: "Dr. R. K. Sharma",
      date: "April 15, 2026",
      excerpt: "Is Mars causing disharmony or delays in your life? Learn how natural ox-blood Moonga balances energetic alignment.",
      image: "red-coral"
    }
  ]
};

window.GemstoneDB = GemstoneDB;
